export const USERS_GET = 'USERS_GET';
export const USERS_SUCCESS = 'USERS_SUCCESS';

export const USERS_FAILURE = 'USERS_FAILURE';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FALIURE = 'LOGIN_FALIURE';

export const ALLPRODUCTS = 'ALLPRODUCTS';
export const ALLPRODUCTS_SUCCESS = 'ALLPRODUCTS_SUCCESS';
export const ALLPRODUCTS_FALIURE = 'ALLPRODUCTS_FALIURE';
